--- #YAML:1.0
name:               Net-Whois-SIDN
version:            0.92
abstract:           Whois output from SIDN in XML format
author:
    - Mark Overmeer
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP:                  0
    XML::Compile:         1.11
    XML::Compile::Cache:  0.9
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
